### PR TITLE
Run chainweb-data executable with green-threading, not OS threads

### PR DESCRIPTION
**Pull request by jwiegley**
I am proposing this PR because I've noticed that `chainweb-data`, when built to use green-threading for concurrency, uses almost no system resources at all. On my iMac Pro, after 24 hours of runtime, it has used a total of 2 minutes of CPU time.

When built with threading, however, it does the same work, but regularly -- and for long periods of time -- fully consumes 6-7 cores on my 10 core machine. I've tried profiling the app, but because the profile only captures what the Haskell code itself is doing, it indicates that nothing is happening (30 seconds of activity after 6 hours of runtime, for example).

So something is happening in the threaded runtime that is busy-waiting the CPU, for reasons that I've yet to discover.

Unless someone can think of a good reason for threading to be enabled for chainweb-data, this seems like an easy and very CPU-saving change with zero effort.

### CODE REVIEW

**Comment by jwiegley** [comment]
Yes, some open questions here:

1. Is it the threaded runtime causing this, or the actual engagement of multiple threads?
2. Without the threaded runtime the executable is still concurrent, but no longer asynchronous. In theory it would reduce catchup by a factor of N, where N is the number of cores available to speed things up.

At some point after travel I'll have to move my chainweb-data out of the way, and spend a few days doing a from-scratch catch up with and without threading.

**Comment by enobayram** [comment]
@jwiegley Just to be 100% clear here, are you observing these bursts of full 6-7 core utilizations during the `listen` operation of an already caught-up CW-D instance?

**Comment by jwiegley** [comment]
@enobayram It was pretty much always taking up that much CPU; I didn't notice it being related to anything output in the logs.

**Comment by enobayram** [comment]
@jwiegley I've been looking into this PR for a few days now in an attempt to understand what exactly is causing this performance issue, but it takes a lot of time to collect data and experiment with build and RTS options since it takes a significant amount of time for `chainweb-data` to start consuming high amounts of CPU.

> Unless someone can think of a good reason for threading to be enabled for chainweb-data, this seems like an easy and very CPU-saving change with zero effort.

I agree that `chainweb-data` is unlikely to benefit from parallelism in most cases. During `fill` and `listen` it's most probably limited by the database and CW-N response times and, as you've noted, it's capable of performing those operations concurrently even when there's no parallelism. That said, I'm not 100% sure how well `postgres-simple` plays with green threads, so I'll measure `fill` times with and without parallelism and if there's no (significant) difference, we can merge this PR and dig deeper into the root cause separately.

**Comment by jwiegley** [comment]
Sounds good, @enobayram!

**Comment by enobayram** [comment]
> I agree that `chainweb-data` is unlikely to benefit from parallelism in most cases

Unfortunately, turns out my expectation was wrong. I've tried starting a `fill` operation over a few CW-D databases that were mostly empty (just had enough blocks to support the `fill` operation). Here's what I tried:

I've added the following to `flake.nix` to enable profiling (I'll push a commit to make that an argument to `flake.nix` in the future): 

```
modules = [
  { enableLibraryProfiling = true;
    enableProfiling = true;
  }
];
```

Then I compiled CW-D from this branch so that threading is disabled. Then the `fill` operation was able to insert 396 items per second.

<details>
  <summary>Collected info</summary>

  Terminal output
  ```
  2023-02-13T15:30:33.263Z [Info] [] Progress: 10440/27549365 (0.04%), ~21 hours remaining at 348 current items per second (348 overall average).
  2023-02-13T15:31:03.263Z [Info] [] Progress: 21960/27549365 (0.08%), ~19 hours remaining at 384 current items per second (366 overall average).
  
  2023-02-13T15:31:33.263Z [Info] [] Progress: 32760/27549365 (0.12%), ~21 hours remaining at 360 current items per second (364 overall average).
  2023-02-13T15:32:03.264Z [Info] [] Progress: 44640/27549365 (0.16%), ~19 hours remaining at 396 current items per second (372 overall average).
  ^C 111,898,592,704 bytes allocated in the heap
    12,076,105,456 bytes copied during GC
        41,221,096 bytes maximum residency (525 sample(s))
         5,501,976 bytes maximum slop
               103 MiB total memory in use (0 MB lost due to fragmentation)
  
                                       Tot time (elapsed)  Avg pause  Max pause
    Gen  0     103664 colls,     0 par    8.129s   9.027s     0.0001s    0.0601s
    Gen  1       525 colls,     0 par    4.824s   5.477s     0.0104s    0.0585s
  
    INIT    time    0.001s  (  0.001s elapsed)
    MUT     time   73.232s  (108.699s elapsed)
    GC      time   12.953s  ( 14.503s elapsed)
    RP      time    0.000s  (  0.000s elapsed)
    PROF    time    0.000s  (  0.000s elapsed)
    EXIT    time    0.000s  (  0.000s elapsed)
    Total   time   86.186s  (123.203s elapsed)
  
    %GC     time       0.0%  (0.0% elapsed)
  
    Alloc rate    1,527,992,579 bytes per MUT second
  
    Productivity  85.0% of total user, 88.2% of total elapsed
  ```

  [chainweb-data-fill-No.prof](https://github.com/kadena-io/chainweb-data/files/10757605/chainweb-data-fill-No.prof.txt)
  ![chainweb-data-fill-No](https://user-images.githubusercontent.com/1258139/219412059-8733651c-247d-464f-bdcc-adc51946ef74.svg)
  
  [fill-psrecord-fill-N1.log](https://github.com/kadena-io/chainweb-data/files/10757597/fill-psrecord-fill-N1.log)
  ![fill-psrecord-fill-No](https://user-images.githubusercontent.com/1258139/219412090-a8dae97b-4dd3-4204-92e6-ad582919f65e.png)

</details>

Then I compared this against a `fill` operation with a binary compiled with `-threaded` and run with `+RTS -N` and then it was able to insert 2081 items per second

<details>
  <summary>Collected info</summary>

  Terminal output
  ```
  2023-02-13T15:34:25.986Z [Info] [] Progress: 64080/15563203 (0.41%), ~2 hours remaining at 2133 current items per second (2133 overall average).
  2023-02-13T15:34:55.990Z [Info] [] Progress: 127440/15563203 (0.82%), ~2 hours remaining at 2112 current items per second (2123 overall average).
  2023-02-13T15:35:25.993Z [Info] [] Progress: 188280/15563203 (1.21%), ~2 hours remaining at 2028 current items per second (2091 overall average).
  2023-02-13T15:35:56.002Z [Info] [] Progress: 249840/15563203 (1.61%), ~2 hours remaining at 2051 current items per second (2081 overall average).
  ^C  86,207,726,792 bytes allocated in the heap
     6,422,523,504 bytes copied during GC
        32,975,608 bytes maximum residency (278 sample(s))
         4,023,560 bytes maximum slop
                98 MiB total memory in use (3 MB lost due to fragmentation)
  
                                       Tot time (elapsed)  Avg pause  Max pause
    Gen  0     28584 colls, 28584 par   197.866s  74.295s     0.0026s    0.0752s
    Gen  1       278 colls,   277 par    6.798s   1.564s     0.0056s    0.0487s
  
    Parallel GC work balance: 54.11% (serial 0%, perfect 100%)
  
    TASKS: 34 (1 bound, 33 peak workers (33 total), using -N8)
  
    SPARKS: 0 (0 converted, 0 overflowed, 0 dud, 0 GC'd, 0 fizzled)
  
    INIT    time    0.003s  (  0.009s elapsed)
    MUT     time  305.932s  ( 46.918s elapsed)
    GC      time  204.664s  ( 75.859s elapsed)
    RP      time    0.000s  (  0.000s elapsed)
    PROF    time    0.000s  (  0.000s elapsed)
    EXIT    time    0.010s  (  0.025s elapsed)
    Total   time  510.609s  (122.811s elapsed)
  
    Alloc rate    281,786,900 bytes per MUT second
  
    Productivity  59.9% of total user, 38.2% of total elapsed
  ```

  [chainweb-data-fill-N.prof](https://github.com/kadena-io/chainweb-data/files/10757623/chainweb-data-fill-N.prof.txt)
  ![chainweb-data-fill-N](https://user-images.githubusercontent.com/1258139/219413086-cfee601c-76f0-483b-b0e6-6d7708f6270d.svg)
  
  [fill-psrecord-fill-N.log](https://github.com/kadena-io/chainweb-dat
  ![fill-psrecord-fill-N](https://user-images.githubusercontent.com/1258139/219413173-c5ec6402-df8a-4040-b71f-c950c4a1a068.png)

</details>

I was curious, so I tried `fill`ing with `-threaded` and `-N1`, so that we use the multi-threaded RTS but with a single core. Then it was able to insert 348 items per second.

<details>
  <summary>Collected info</summary>

  Terminal output
  ```
  2023-02-13T15:17:32.760Z [Info] [] Progress: 10440/3440627 (0.30%), ~2 hours remaining at 348 current items per second (348 overall average).                                                                                               
  2023-02-13T15:18:02.760Z [Info] [] Progress: 20880/3440627 (0.61%), ~2 hours remaining at 348 current items per second
  (348 overall average).                                                                                               
  2023-02-13T15:18:32.764Z [Info] [] Progress: 31680/3440627 (0.92%), ~2 hours remaining at 360 current items per second (352 overall average).                                                                                               
  2023-02-13T15:19:02.765Z [Info] [] Progress: 42120/3440627 (1.22%), ~2 hours remaining at 348 current items per second (351 overall average).                                                                                               
  ^C 102,962,859,760 bytes allocated in the heap                                                                        
    10,204,597,448 bytes copied during GC                                                                               
        34,402,096 bytes maximum residency (630 sample(s))                                                              
        4,375,552 bytes maximum slop                                                                                   
                87 MiB total memory in use (0 MB lost due to fragmentation)                                             
                                                                                                                        
                                      Tot time (elapsed)  Avg pause  Max pause                                         
    Gen  0     95218 colls,     0 par    8.158s   9.888s     0.0001s    0.0191s                                         
    Gen  1       630 colls,     0 par    4.474s   5.071s     0.0080s    0.0556s                                         
                                                                                                                        
    TASKS: 6 (1 bound, 5 peak workers (5 total), using -N1)                                                             
                                                                                                                        
    SPARKS: 0 (0 converted, 0 overflowed, 0 dud, 0 GC'd, 0 fizzled)                                                     
                                                                                                                        
    INIT    time    0.003s  (  0.017s elapsed)                                                                          
    MUT     time   72.657s  (107.657s elapsed)                                                                          
    GC      time   12.632s  ( 14.959s elapsed)                                                                          
    RP      time    0.000s  (  0.000s elapsed)                                                                          
    PROF    time    0.000s  (  0.000s elapsed)                                                                          
    EXIT    time    0.000s  (  0.001s elapsed)                                                                          
    Total   time   85.292s  (122.634s elapsed)                                                                          
                                                                                                                        
    Alloc rate    1,417,115,814 bytes per MUT second                                                                    
                                                                                                                        
    Productivity  85.2% of total user, 87.8% of total elapsed                                                           
  ```

  [chainweb-data-fill-N1.prof](https://github.com/kadena-io/chainweb-data/files/10757679/chainweb-data-fill-N1.prof.txt)
  ![chainweb-data-fill-N1](https://user-images.githubusercontent.com/1258139/219414225-36e40231-fc5c-4f39-aa23-d65aa7b88670.svg)

  [fill-psrecord-fill-N1.log](https://github.com/kadena-io/chainweb-data/files/10757682/fill-psrecord-fill-N1.log)
  ![fill-psrecord-fill-N1](https://user-images.githubusercontent.com/1258139/219414277-0a5bc897-8c2f-45b8-85be-69d451d83092.png)

</details>

But then I've noticed that we were using `getNumCapabilities` to determine the Postgres connection pool size, which is not really the number of cores on the machine but the number of threads available to the Haskell process. So I went ahead and [replaced `getNumCapabilities` with `getNumProcessors`](https://github.com/kadena-io/chainweb-data/pull/93/commits/dc3e41638d30be225e04ee9b3a4aa5274c0b0f80) to give the non-threaded binary a fair chance. But even then, without threading it was able to insert 540 items per second. Only a slight improvement.

<details>
  <summary>Collected info</summary>

  Terminal output
  ```
  2023-02-15T17:02:00.530Z [Info] [] Progress: 16200/60845997 (0.03%), ~31 hours remaining at 540 current items per second (540 overall average).
  2023-02-15T17:02:30.531Z [Info] [] Progress: 32040/60845997 (0.05%), ~31 hours remaining at 528 current items per second (534 overall average).
  2023-02-15T17:03:00.532Z [Info] [] Progress: 48240/60845997 (0.08%), ~31 hours remaining at 540 current items per second (536 overall average).
  2023-02-15T17:03:30.532Z [Info] [] Progress: 64440/60845997 (0.11%), ~31 hours remaining at 540 current items per second (537 overall average).
    164,172,094,432 bytes allocated in the heap
    15,355,988,288 bytes copied during GC
        32,917,360 bytes maximum residency (1017 sample(s))
        5,040,280 bytes maximum slop
                86 MiB total memory in use (0 MB lost due to fragmentation)

                                      Tot time (elapsed)  Avg pause  Max pause
    Gen  0     151819 colls,     0 par    7.177s   7.277s     0.0000s    0.0014s
    Gen  1      1017 colls,     0 par    4.773s   4.774s     0.0047s    0.0181s

    INIT    time    0.001s  (  0.001s elapsed)
    MUT     time   78.561s  (109.327s elapsed)
    GC      time   11.949s  ( 12.051s elapsed)
    RP      time    0.000s  (  0.000s elapsed)
    PROF    time    0.000s  (  0.000s elapsed)
    EXIT    time    0.000s  (  0.000s elapsed)
    Total   time   90.512s  (121.379s elapsed)

    %GC     time       0.0%  (0.0% elapsed)

    Alloc rate    2,089,728,856 bytes per MUT second

    Productivity  86.8% of total user, 90.1% of total elapsed
  ```

  [chainweb-data-fill-No-proc.prof](https://github.com/kadena-io/chainweb-data/files/10757709/chainweb-data-fill-No-proc.prof.txt)
  ![chainweb-data-fill-No-proc](https://user-images.githubusercontent.com/1258139/219415207-95a8ea04-759f-4417-a2a6-7e0556aca5df.svg)
  [fill-psrecord-fill-No-proc.log](https://github.com/kadena-io/chainweb-data/files/10757710/fill-psrecord-fill-No-proc.log)
  ![fill-psrecord-fill-No-proc](https://user-images.githubusercontent.com/1258139/219415241-ba22e895-9d23-4ddf-a399-71e0336a77d2.png)

</details>

So, it seems like, with the way the `fill` operation is currently implemented, multiple threads are essential for the `fill` performance.

**Comment by jwiegley** [comment]
@enobayram When we say "essential", are there scenarios where the slower performance of one thread would be unable to provide necessary service? Is there a need for filling to happen quickly?

**Comment by enobayram** [comment]
@jwiegley, you're right that the extra performance isn't essential for CW-D per se. During normal operation, CW-D receives less than 1 block on average, which is still 350 times less than what it can handle during a single-threaded fill. I also don't think filling has to happen quickly. Currently, `fill` takes 10-20 hours, so, when single threaded, it should take 2-4 days, which is not the end of the world, but is also a non-trivial difference for anyone that needs to deal with it.

I think we should also consider how single-threading will affect the occasional migration that might be necessary when we're pushing new features, like how the new `transfers` table required the `backfill-transfers` operation. 

I wonder whether we should settle on a middle ground here where we keep compiling with `-threaded`, but use `+RTS -N1` by default so that the users can still pass `+RTS -N` for `fill`(-like) operations. I'll gather some measurements on how `-N1` behaves during `serve` (and `listen`) compared to no `-threaded` and `-N`.

**Comment by enobayram** [comment]
@jwiegley Since https://github.com/kadena-io/chainweb-data/pull/136, it's possible to build `chainweb-data` with `nix-build -A default --arg threaded false` and obtain a binary that has the single-threaded runtime. So I'll close this PR for now with the intention to come back and try to diagnose the underlying performance issue with the multi-threaded runtime later on.

**Comment by jwiegley** [comment]
Thank you, @enobayram! That works for me.

**Pull request closed without merging**
